"""initial schema

Revision ID: c0b893910048
Revises:
Create Date: 2026-07-10 19:33:29.920275

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0b893910048"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("condition_type", sa.String(length=50), nullable=False),
        sa.Column("condition_value", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("defense", sa.Integer(), nullable=True),
        sa.Column("attack", sa.Integer(), nullable=True),
        sa.Column("pet_power", sa.Integer(), nullable=True),
        sa.Column("required_level", sa.Integer(), nullable=True),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "UNCOMMON", "RARE", "EPIC", "LEGENDARY", name="rarity"),
            nullable=True,
        ),
        sa.Column("available_in_shop", sa.Boolean(), nullable=True),
        sa.Column(
            "theme",
            sa.Enum(
                "COMMON",
                "WINTER",
                "SUMMER",
                "SPRING",
                "FALL",
                "ASIAN",
                "MEDIEVAL",
                "HALLOWEEN",
                "CHRISTMAS",
                name="itemtheme",
            ),
            nullable=True,
        ),
        sa.Column(
            "item_type",
            sa.Enum(
                "WEAPON",
                "ARMOR",
                "ACCESSORY",
                "PET",
                "CONSUMABLE",
                "MISC",
                name="itemtype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "revoked_tokens",
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revoked_tokens_jti"), "revoked_tokens", ["jti"], unique=True
    )
    op.create_table(
        "rewards",
        sa.Column("gold", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("health_points", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shop_rotations",
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "theme",
            sa.Enum(
                "COMMON",
                "WINTER",
                "SUMMER",
                "SPRING",
                "FALL",
                "ASIAN",
                "MEDIEVAL",
                "HALLOWEEN",
                "CHRISTMAS",
                name="itemtheme",
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_points", sa.Integer(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column("gold", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "equipped_items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "slot",
            sa.Enum("HELMET", "ARMOR", "ACCESSORY", "WEAPON", "PET", name="slottype"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "friendships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("friend_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "DECLINED", name="friendshipstatus"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habits",
        sa.Column(
            "habit_type",
            sa.Enum("POSITIVE", "NEGATIVE", "NEUTRAL", name="habittype"),
            nullable=True,
        ),
        sa.Column(
            "habit_size",
            sa.Enum("SMALL", "MEDIUM", "BIG", "LARGE", name="size"),
            nullable=True,
        ),
        sa.Column("overfullfillment", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("TODO", "FAILED", "COMPLETED", name="habitstatus"),
            nullable=True,
        ),
        sa.Column("streak", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "TASK_REMINDER",
                "STREAK_REMINDER",
                "NEWS",
                "FRIEND_REQUEST",
                "SYSTEM",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reward_achievement",
        sa.Column("reward_id", sa.Integer(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reward_id"],
            ["rewards.id"],
        ),
        sa.PrimaryKeyConstraint("reward_id", "achievement_id"),
    )
    op.create_table(
        "reward_item",
        sa.Column("reward_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reward_id"],
            ["rewards.id"],
        ),
        sa.PrimaryKeyConstraint("reward_id", "item_id"),
    )
    op.create_table(
        "shop_items",
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "UNCOMMON", "RARE", "EPIC", "LEGENDARY", name="rarity"),
            nullable=True,
        ),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column(
            "status",
            sa.Enum("TODO", "IN_PROGRESS", "COMPLETED", name="taskstatus"),
            nullable=True,
        ),
        sa.Column(
            "task_type", sa.Enum("DAILY", "REGULAR", name="tasktype"), nullable=True
        ),
        sa.Column(
            "task_size",
            sa.Enum("SMALL", "MEDIUM", "BIG", "LARGE", name="size"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_achievements",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "achievement_id"),
    )
    op.create_table(
        "user_notification_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "TASK_REMINDER",
                "STREAK_REMINDER",
                "NEWS",
                "FRIEND_REQUEST",
                "SYSTEM",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "notification_type", name="_user_notification_type_uc"
        ),
    )
    op.create_table(
        "shop_rotation_items",
        sa.Column("rotation_id", sa.Integer(), nullable=False),
        sa.Column("shop_item_id", sa.Integer(), nullable=False),
        sa.Column("is_random_common", sa.Boolean(), nullable=True),
        sa.Column("is_themed", sa.Boolean(), nullable=True),
        sa.Column("slot_in_display", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["rotation_id"],
            ["shop_rotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_item_id"],
            ["shop_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rotation_id", "shop_item_id", name="unique_rotation_shop_item"
        ),
    )
    op.create_table(
        "sub_tasks",
        sa.Column(
            "status",
            sa.Enum("TODO", "IN_PROGRESS", "COMPLETED", name="taskstatus"),
            nullable=True,
        ),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sub_tasks")
    op.drop_table("shop_rotation_items")
    op.drop_table("user_notification_preferences")
    op.drop_table("user_achievements")
    op.drop_table("tasks")
    op.drop_table("shop_items")
    op.drop_table("reward_item")
    op.drop_table("reward_achievement")
    op.drop_table("notifications")
    op.drop_table("inventory_items")
    op.drop_table("habits")
    op.drop_table("friendships")
    op.drop_table("equipped_items")
    op.drop_table("users")
    op.drop_table("shop_rotations")
    op.drop_table("rewards")
    op.drop_index(op.f("ix_revoked_tokens_jti"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_table("items")
    op.drop_table("achievements")
    # ### end Alembic commands ###
